name: snpgenie
version: 'latest'
#version-script: git describe --abbrev=1 --tags
summary: tool for microbial variant calling
description: |
  snpgenie is a tool for microbial variant calling
  and phylogenetic analysis from raw read data.
base: core18
grade: stable
confinement: strict
icon: gui/icon.png

apps:
  snpgenie:
    command: desktop-launch $SNAP/bin/snpgenie-gui
    plugs: [desktop,home]
#    environment:
#      LD_LIBRARY_PATH: $SNAP/usr/lib/ncbi-blast+
parts:
  snpgenie:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
      - bcftools
      - samtools
      - bwa
#      - raxml
    python-packages:
      - PySide2
    after: [desktop-qt5]

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
        - libgtk2.0-0
        - libqt5svg5 # for loading icon themes which are svg
        - try: [appmenu-qt5] # not available on core18
        - locales-all
        - libcairo-gobject2
