name: snpgenie
version: '0.2.0-28-g7b45938'
#version-script: git describe --abbrev=1 --tags
summary: tool for microbial variant calling
description: |
  snpgenie is a tool for microbial variant calling
  and phylogenetic analysis from raw read data.
base: core18
grade: stable
confinement: strict
icon: snap/gui/icon.png

apps:
  snpgenie:
    command: desktop-launch $SNAP/bin/snpgenie-gui
    extensions:
      - kde-neon
    plugs:
      - home
      - opengl
      - network
      - network-bind
      - network-control
      - mount-observe
#    environment:
#      LD_LIBRARY_PATH: $SNAP/usr/lib/ncbi-blast+

parts:
  snpgenie:
    plugin: python
    source: .
    stage-packages:
      - bcftools
      - samtools
      - bwa
      - fasttree
